### ISSUE TITLE
PR2 database filtering criteria

### ISSUE THREAD

**Issue by kfgibson** [pr2database/pr2database#22]
Hello,

I am wondering if there is more information available somewhere on the filtering criteria that PR2 uses to include sequences? I have read the 2013 paper and I see that there have been some changes to the sequence lengths included and the number of ambiguous bases permitted. I am a little bit confused because I am also using the Silva 18S database and there are many sequences in Silva-Ref that are not in PR2. For example, the accession ID KP404780 is absent from PR2 v. 4.12  (but is included in Silva-Ref v. 132) and is annotated in GenBank as an 18S eukaryotic sequence and meets the PR2 criteria for sequence length and ambiguous bases. 

Sorry if this is a silly question and thank you in advance!

**Comment by vaulot** [comment]
Hi Kate
This is indeed a good question.  

PR2 does not aims at being inclusive of all GenBank sequences in contrast to Silva.  So many 18S/Silva sequences are not in PR2.  We aim to have representative sequences from all phylogenetic groups and to have accurate taxonomic annotation for each of the sequences that are in PR2 (which is not the case for GenBank/Silva where many sequences are just annotated as eukaryotes).  For some groups (e.g. Haptophyta or Chlorophyta) specific annotation works have allowed to have most of the available GenBank sequences annotated and included in GenBank.  However this represents a point of time, and sequences that appeared since the annotation work has been done have not been included.  Indeed this is the aim of the EukRef workshops to annotate entire groups and to update the available sequences.  We try also to draw on recent papers to include new sequences, so if you have a group for which you have annotation you are more than welcome to contact us so that the new sequences can be incorporated in PR2.  For example, the sequence you mention, KP404780, is a cryptophyte and until now we did not had anyone annotating this division.

Daniel

**Comment by kfgibson** [comment]
Hi Daniel,

Thank you for taking the time to reply. I do want to clarify one thing for myself. For the groups with specific annotation works, does this just mean that there are enough species in the group that have sequences with known annotation to be able to annotate the similar GenBank sequences? So the approach of the PR2 database is to use the annotation work of a particular group to annotate the GenBank sequences that are similar to the annotated sequences in that group? I am curious then about the GenBank sequences that are included in the groups that have not yet been annotated e.g. the cryptophytes. There are still a large number of sequences from the cryptophytes that are included in PR2 and it is unclear to me how these sequences were selected to be included. 

Thanks,
Kate

**Comment by vaulot** [comment]
Hi Kate

This is a bit complex question, because for some groups like Cryptophytes sequences were selected and annotated when PR2 was set (roughly 2010-2012) and I must say that I do not know who annotated initially the Cryptos but I can find out if you want.  If you are interested by a group that has not been updated recently, the preferred approach would be to use the EukRef approach which is I admit a bit complex since you need to build trees etc... but we are aiming at making it more streamlined: http://eukref.org/pipeline/.  

Daniel
