### ISSUE TITLE
Training set derived from PR2 for IDTAXA (DECIPHER)

### ISSUE THREAD

**Issue by Caro0026** [pr2database/pr2database#26]
Hi Daniel,

I was wondering whether there was a training set available derived from the PR2 database adapted for the idtaxa function (DECIPHER package) or whether there was a tutorial/ some documentation providing clues on how to create it from the original database.

Thanks for your help!

Caroline

**Comment by vaulot** [comment]
Hi Caroline

Here is a piece of code that I wrote 2 years ago.  I did not use since so cannot guarantee it will work.  If you improve, it will be nice to post here... Good luck. Daniel


# Init
```{r init, message=FALSE, warning=FALSE, eval=TRUE}

# Libraries for bioinfo ----------------------------------------------------

  library("dada2")
  library("Biostrings")
  library("taxa")
  library("scales")  # necessary to transform heatmaps

# Libraries tidyr ---------------------------------------------------------

  library("ggplot2") 
  library("dplyr")   
  library("readxl")
  library("tibble")
  library("readr")
  library("purrr")
  library("forcats")
  library("lubridate")
  library("stringr")
  library(openxlsx)
  library(DECIPHER)
```

# Testing running a training set on PR2

Total number of sequences eliminated : 72786

Show in New WindowClear OutputExpand/Collapse Output
  A training set of class 'Taxa'
   * K-mer size: 8
   * Number of rank levels: 9
   * Total number of sequences: 102685
   * Number of taxonomic groups: 45750
   * Number of problem groups: 117
   * Number of problem sequences: 363
   
```{r Training, eval=FALSE}

seqs <- readDNAStringSet("pr2_version_4.12.0_dada2.fasta.gz")
# obtain the taxonomic assignments
groups <- names(seqs) # sequence names
# assume the taxonomy begins with 'Root;'
groups <- gsub("(.*)(Eukaryota;)", "\\2", groups) # extract the group label

# All taxos must start with "Root;"
groups <- str_replace(groups,"Eukaryota","Root;Eukaryota")
names(seqs)<-groups

groupCounts <- table(groups)
u_groups <- names(groupCounts) # unique groups
length(u_groups) # number of group

taxid <- NULL

maxGroupSize <- 20 # max sequences per label (>= 1)
remove <- logical(length(seqs))
for (i in which(groupCounts > maxGroupSize)) {
  index <- which(groups==u_groups[i])
  keep <- sample(length(index), maxGroupSize)
  remove[index[-keep]] <- TRUE
}
sum(remove) # number of sequences eliminated
# > sum(remove) # number of sequences eliminated
# [1] 72123

maxIterations <- 3 # must be >= 1
allowGroupRemoval <- FALSE

probSeqsPrev <- integer() # suspected problem sequences from prior iteration

for (i in seq_len(maxIterations)) {
  cat("Training iteration: ", i, "\n", sep="")
  # train the classifier
  trainingSet <- LearnTaxa(seqs[!remove],  names(seqs)[!remove],taxid)
  # look for problem sequences
  probSeqs <- trainingSet$problemSequences$Index
  if (length(probSeqs)==0) {
    cat("No problem sequences remaining.\n")
    break
  } else if (length(probSeqs)==length(probSeqsPrev) && all(probSeqsPrev==probSeqs)) {
    cat("Iterations converged.\n")
    break
  }
  if (i==maxIterations)
    break
    probSeqsPrev <- probSeqs
    # remove any problem sequences
    index <- which(!remove)[probSeqs]
    remove[index] <- TRUE # remove all problem sequences
    if (!allowGroupRemoval) {
    # replace any removed groups
    missing <- !(u_groups %in% groups[!remove])
    missing <- u_groups[missing]
    if (length(missing) > 0) {
      index <- index[groups[index] %in% missing]
      remove[index] <- FALSE # don't remove
    }
  }
}

sum(remove) # total number of sequences eliminated
length(probSeqs) # number of remaining problem sequences

saveRDS(trainingSet, "decipher_training_18S_PR2.4.12.0.rds")
```
Training set stats
```{r training stats, eval=TRUE}
trainingSet <- readRDS("decipher_training_18S_PR2.4.12.0.rds")
trainingSet
plot(trainingSet)

```

Identifying problem sequences

```{r problems}
problems_seq <- data.frame(trainingSet$problemSequences) %>% 
                dplyr::mutate(Expected= str_extract(Expected,";[A-Z]{1}[a-z0-9_.]+;$"))

problems_groups <- data.frame(trainingSet$problemGroups)
knitr::kable(problems_seq)
```


Use training set to assign sequences

```{r Idtaxa}
test <- readDNAStringSet("otu_taxo.fasta.gz")
ids <- IdTaxa(test,
        trainingSet,
        type="extended",
        strand="top",
        threshold=0)

  ids
  ids[[1]]
  # plot(ids)
  
  output <- data.frame(decipher=purrr::map_chr(ids,function (id) {
                      paste(id$taxon[[8]],
                      " (",
                      round(id$confidence[[8]], digits=1),
                      "%)",
                      sep="",
                      collapse="; ")
                    }))
  output <- tibble::rownames_to_column(output, var="dada2") %>%
            dplyr::mutate (dada2 = str_extract(dada2,"(\\|[A-Z]){1}[^|]+$"))
  
  knitr::kable(output)
  
```


[otu_taxo.fasta.gz](https://github.com/pr2database/pr2database/files/4929856/otu_taxo.fasta.gz)

**Comment by Caro0026** [comment]
Thanks a lot Daniel!

**Comment by digitalwright** [comment]
FYI, I posted a PR2 training set on the [DECIPHER website](http://DECIPHER.codes).

**Comment by vaulot** [comment]
Hi Erik, thanks a lot. I posted the link in the latest release info.  Cheers. Daniel

**Comment by vaulot** [comment]
Hi Erik
I have now posted a small tutorial to do a trained dataset from PR2: https://pr2database.github.io/pr2database/articles/pr2_04_decipher.html

Let me know of anything needs to be changed.  Cheers.

**Comment by vaulot** [comment]
Hi Erik

Thanks for the comments.

- For the first issue, I am not really sure what you meant since I only use IDTAXA in the title of the paper... If you can point it better to me.
- For the second issue I answered on the Bioconductor forum.  In brief PR2 does not use a taxon table but a taxonomy table. So there are no ranks nor taxon_id in the format that is required by LearnTaxa function (parameter rank =). 

Cheers. Daniel

**Comment by digitalwright** [comment]
Hi Daniel,

Thanks for taking a second look at this issue.

Regarding the first point, the [link](https://pr2database.github.io/pr2database/articles/pr2_04_decipher.html) posted above mentions "IDTax" a couple times, rather than "IDTAXA" (the algorithm name) or "IdTaxa" (the function name).

Regarding the second point, there is an example of "Creating a taxid file" for a fixed rank taxonomy in the [Classify Sequences](https://DECIPHER.codes/Documentation-ClassifySequences.html) vignette. As I understand the PR2, it should be feasible.

Erik

**Comment by vaulot** [comment]
Hi Erik

- I corrected the tutorial for the IdTaxa mispelling. This will become visible with the next release 5.1 in a few days/weeks.
- Next trained dataset will hopefully contain also a taxid identifier for each taxon.

Daniel
