### ISSUE TITLE
problem with Fragilariopsis

### ISSUE THREAD

**Issue by JJPierellaKarlusich** [pr2database/pr2database#32]
When reannotating the Tara Oceans V9 metabarcodes using PR2 v4.14, we noted the lack of Fragilariopsis in the new annotation. Using the most abundant Fragilariopsis OTU in the original dataset, we found that the best hits in PR2 v4.14 correspond to 100% identity to a group of sequences including a Dinophyceae (obviously an error in PR2 v4.14) and a bunch of diatom reference sequences poorly assigned as 'Raphid-pennate_X_sp', in addition to a Fragilariopsis sequence:

query:
>1533bc0882cb58d28b5c56f49269c1c2
gtcgcacctaccgattgaatggtccggtgaagcctcgggattgtggttagtttcctttattggaagttagtcgcgagaacttgtctaaaccttatcatttagaggaaggtgaagtcgtaacaaggtttcc

Subjects (100 % id):
KC771185.1.1787_U;tax=k:Eukaryota,d:Stramenopiles,p:Ochrophyta,c:Bacillariophyta,o:Bacillariophyta_X,f:Raphid-pennate,g:Raphid-pennate_X,s:Raphid-pennate_X_sp.
EF100371.1.1232_U;tax=k:Eukaryota,d:Stramenopiles,p:Ochrophyta,c:Bacillariophyta,o:Bacillariophyta_X,f:Raphid-pennate,g:Raphid-pennate_X,s:Raphid-pennate_X_sp.
KC771174.1.1777_U;tax=k:Eukaryota,d:Stramenopiles,p:Ochrophyta,c:Bacillariophyta,o:Bacillariophyta_X,f:Raphid-pennate,g:Raphid-pennate_X,s:Raphid-pennate_X_sp.
KC771149.1.1790_U;tax=k:Eukaryota,d:Stramenopiles,p:Ochrophyta,c:Bacillariophyta,o:Bacillariophyta_X,f:Raphid-pennate,g:Raphid-pennate_X,s:Raphid-pennate_X_sp.
KC771193.1.1786_U;tax=k:Eukaryota,d:Stramenopiles,p:Ochrophyta,c:Bacillariophyta,o:Bacillariophyta_X,f:Raphid-pennate,g:Raphid-pennate_X,s:Raphid-pennate_X_sp.
KC771190.1.1789_U;tax=k:Eukaryota,d:Stramenopiles,p:Ochrophyta,c:Bacillariophyta,o:Bacillariophyta_X,f:Raphid-pennate,g:Raphid-pennate_X,s:Raphid-pennate_X_sp.
KC771168.1.1787_U;tax=k:Eukaryota,d:Stramenopiles,p:Ochrophyta,c:Bacillariophyta,o:Bacillariophyta_X,f:Raphid-pennate,g:Raphid-pennate_X,s:Raphid-pennate_X_sp.
EF140623.1.1779_U;tax=k:Eukaryota,d:Stramenopiles,p:Ochrophyta,c:Bacillariophyta,o:Bacillariophyta_X,f:Raphid-pennate,g:Fragilariopsis,s:Fragilariopsis_curta
KJ757846.1.1801_U;tax=k:Eukaryota,d:Alveolata,p:Dinoflagellata,c:Dinophyceae,o:Dinophyceae_X,f:Dinophyceae_XX,g:Dinophyceae_XXX,s:Dinophyceae_XXX_sp.
KJ757881.1.1791_U;tax=k:Eukaryota,d:Stramenopiles,p:Ochrophyta,c:Bacillariophyta,o:Bacillariophyta_X,f:Raphid-pennate,g:Raphid-pennate_X,s:Raphid-pennate_X_sp.
KJ758129.1.1800_U;tax=k:Eukaryota,d:Stramenopiles,p:Ochrophyta,c:Bacillariophyta,o:Bacillariophyta_X,f:Raphid-pennate,g:Raphid-pennate_X,s:Raphid-pennate_X_sp.
KJ758140.1.1795_U;tax=k:Eukaryota,d:Stramenopiles,p:Ochrophyta,c:Bacillariophyta,o:Bacillariophyta_X,f:Raphid-pennate,g:Raphid-pennate_X,s:Raphid-pennate_X_sp.
KJ758229.1.1792_U;tax=k:Eukaryota,d:Stramenopiles,p:Ochrophyta,c:Bacillariophyta,o:Bacillariophyta_X,f:Raphid-pennate,g:Fragilariopsis,s:Fragilariopsis_sp.

I wonder whether there are more mistakes in the last PR2 version. Maybe a way of checking this is by running some re-assignment test, or random checks to spot other mistakes, or maybe by detecting cases where the taxonomy of the best hit sequences (with identical %id) are strongly contradictory  - a dinoflagellate followed by diatoms as in this case.

**Comment by vaulot** [comment]
Dear Juan

This is an interesting case which shows that V9 in some case is not really a good marker.  I aligned the sequences that matched at 100% your Tara barcode.   This set of sequence contains only one Fragilariopsis strain (sequence in bold in the list).  Other are Fragiliariopsis environmental sequences (so they have been annotated as Fragilariopsis based on their similarity to the strain (see in bold in list of sequences below).  Outside the V9 in the V4 region, there are at least 3 sequences annotated as  Raphid-pennate_X_sp. which have a very different signature from Fragilariopsis . 

The Dino sequence is interesting because it is 100% similar to your barcode in the V9 region but very different outside V9.  In fact, doing a BLAST shows that it is most similar (still lower than 96% to some dino sequences).  I suspect it could be a chimera and I will quarantine for the next version of PR2.

When you use dada2 assignTaxonomy (same as RDP classifier) or DECIPHER using your sequence against PR2, it finds correctly Fragilariopsis... 

Final word concerning "mistakes" in PR2. It is a bit more complex.   PR2 rely on expert annotation for specific groups as it is the best way to have a solid database.  In this process some sequences are flagged as suspicious and removed or reassigned.  In the case of the dinoflagellate even doing a BLAST against the database will not work because it will hit other dinoflagellate.  One solution would be to run a chimera detection program, but the output needs to be thoroughly processed to make sure that bona fide sequences are not excluded.  So the PR2 annotation should always be taken with a grain of salt... and we are welcoming experts to help us improving it.  Diatoms were one of the group on which people worked during the last EukRef workshop but unfortunately things were not finalized....

![image](https://user-images.githubusercontent.com/24701681/146482174-8d74c3b2-9cc9-4475-944a-7a5cc551e135.png)
![image](https://user-images.githubusercontent.com/24701681/146483975-bdd860e0-c9e2-4bb4-9114-9731b027b53a.png)
![image](https://user-images.githubusercontent.com/24701681/146484623-66b7f907-619c-4059-9a58-a3fe0fbceba3.png)

**Comment by vaulot** [comment]
The dino sequence will be labelled as chimera in version 5.0.0 soon to be released.
